server:
  port: 8080

spring:
  application:
    name: catalog
  datasource:
    username: anafernandes
    url: jdbc:postgresql://localhost:5432/catalog
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: catalog-service
            client-secret: 8B0qRaYyUaq91OLGivkJrkclESVPBVWr
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/CatalogKeycloak
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/CatalogKeycloak

  flyway:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

resilience4j.retry:
  instances:
    getStockRetry:
      maxRetryAttempts: 3
      waitDuration: 10s




