server:
  port: 8081
spring:
  application:
    name: stock
  datasource:
    username: anafernandes
    url: jdbc:postgresql://localhost:5432/stock
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange: stock.exchange
    queue: stock.queue
    routingkey: stock.routingkey

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
